<div class="col-md-4"><div class="form-group mb-3"><label class="form-label">Customer</label><select class="form-control" name="customer_id"><option value="">Select..</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string) old('customer_id', $row?->customer_id) === (string) $customer->id)>{{ $customer->name }}</option>@endforeach</select></div></div>
<div class="col-md-4"><div class="form-group mb-3"><label class="form-label">Customer Name</label><input type="text" name="customer_name" class="form-control" value="{{ old('customer_name', $row?->customer_name) }}"></div></div>
<div class="col-md-4"><div class="form-group mb-3"><label class="form-label">Phone</label><input type="text" name="phone" class="form-control" value="{{ old('phone', $row?->phone) }}"></div></div>
<div class="col-md-3"><div class="form-group mb-3"><label class="form-label">Invoice ID</label><input type="text" name="invoice_id" class="form-control" value="{{ old('invoice_id', $row?->invoice_id) }}"></div></div>
<div class="col-md-3"><div class="form-group mb-3"><label class="form-label">Due Date</label><input type="date" name="due_date" class="form-control" value="{{ old('due_date', optional($row?->due_date)->format('Y-m-d') ?: now()->format('Y-m-d')) }}"></div></div>
<div class="col-md-2"><div class="form-group mb-3"><label class="form-label">Amount *</label><input type="number" step="0.01" min="0" name="amount" class="form-control" value="{{ old('amount', $row?->amount) }}" required></div></div>
<div class="col-md-2"><div class="form-group mb-3"><label class="form-label">Paid</label><input type="number" step="0.01" min="0" name="paid_amount" class="form-control" value="{{ old('paid_amount', $row?->paid_amount) }}"></div></div>
<div class="col-md-2"><div class="form-group mb-3"><label class="d-block form-label">Status</label><label class="switch"><input type="checkbox" name="status" value="1" @if(old('status', $row?->status ?? 1)) checked @endif><span class="slider round"></span></label></div></div>
<div class="col-md-12"><div class="form-group mb-3"><label class="form-label">Note</label><textarea name="note" class="form-control" rows="4">{{ old('note', $row?->note) }}</textarea></div></div>
