<div class="col-md-4"><div class="form-group mb-3"><label class="form-label">Employee *</label><select class="form-control" name="employee_id" required><option value="">Select..</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((string) old('employee_id', $salaryStructure?->employee_id) === (string) $employee->id)>{{ $employee->name }}</option>@endforeach</select></div></div>
<div class="col-md-4"><div class="form-group mb-3"><label class="form-label">Basic Salary</label><input type="number" step="0.01" min="0" name="basic_salary" class="form-control" value="{{ old('basic_salary', $salaryStructure?->basic_salary) }}"></div></div>
<div class="col-md-4"><div class="form-group mb-3"><label class="form-label">House Rent</label><input type="number" step="0.01" min="0" name="house_rent" class="form-control" value="{{ old('house_rent', $salaryStructure?->house_rent) }}"></div></div>
<div class="col-md-4"><div class="form-group mb-3"><label class="form-label">Medical Allowance</label><input type="number" step="0.01" min="0" name="medical_allowance" class="form-control" value="{{ old('medical_allowance', $salaryStructure?->medical_allowance) }}"></div></div>
<div class="col-md-4"><div class="form-group mb-3"><label class="form-label">Transport Allowance</label><input type="number" step="0.01" min="0" name="transport_allowance" class="form-control" value="{{ old('transport_allowance', $salaryStructure?->transport_allowance) }}"></div></div>
<div class="col-md-4"><div class="form-group mb-3"><label class="form-label">Other Allowance</label><input type="number" step="0.01" min="0" name="other_allowance" class="form-control" value="{{ old('other_allowance', $salaryStructure?->other_allowance) }}"></div></div>
<div class="col-md-4"><div class="form-group mb-3"><label class="form-label">Effective Date</label><input type="date" name="effective_date" class="form-control" value="{{ old('effective_date', optional($salaryStructure?->effective_date)->format('Y-m-d')) }}"></div></div>
<div class="col-md-12"><div class="form-group mb-3"><label class="form-label">Notes</label><textarea name="notes" class="form-control" rows="4">{{ old('notes', $salaryStructure?->notes) }}</textarea></div></div>
<div class="col-md-3"><div class="form-group mb-3"><label class="d-block form-label">Status</label><label class="switch"><input type="checkbox" name="status" value="1" @if(old('status', $salaryStructure?->status ?? 1)) checked @endif><span class="slider round"></span></label></div></div>
