@extends('backEnd.layouts.master')
@section('title','Payroll Manage')

@section('content')
<div class="container-fluid">
    <div class="row"><div class="col-12"><div class="page-title-box"><div class="page-title-right"><a href="{{ route('hr.payroll.create') }}" class="btn btn-primary rounded-pill">Create</a></div><h4 class="page-title">Payroll Manage</h4></div></div></div>
    <div class="card"><div class="card-body">
        <form class="mb-3"><div class="row g-3"><div class="col-md-3"><select class="form-control" name="employee_id"><option value="">All Employees</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((string) request('employee_id') === (string) $employee->id)>{{ $employee->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-control" name="status"><option value="">All Status</option>@foreach(['pending','paid','hold'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="col-md-2"><input type="number" class="form-control" name="month" min="1" max="12" value="{{ request('month') }}" placeholder="Month"></div><div class="col-md-2"><input type="number" class="form-control" name="year" min="2000" max="2100" value="{{ request('year') }}" placeholder="Year"></div><div class="col-md-2"><button class="btn btn-primary w-100">Filter</button></div></div></form>
        <div class="table-responsive"><table class="table table-striped align-middle"><thead><tr><th>Employee</th><th>Period</th><th>Basic</th><th>Bonus</th><th>Deduction</th><th>Net</th><th>Status</th><th>Action</th></tr></thead><tbody>@foreach($data as $value)<tr><td>{{ $value->employee?->name }}</td><td>{{ str_pad((string) $value->month, 2, '0', STR_PAD_LEFT) }}/{{ $value->year }}</td><td>{{ number_format((float) $value->basic_salary, 2, '.', '') }}</td><td>{{ number_format((float) $value->bonus, 2, '.', '') }}</td><td>{{ number_format((float) $value->deduction, 2, '.', '') }}</td><td>{{ number_format((float) $value->net_salary, 2, '.', '') }}</td><td><span class="badge bg-info text-dark">{{ ucfirst($value->status) }}</span></td><td class="d-flex gap-1"><a href="{{ route('hr.payroll.payslip', $value->id) }}" class="btn btn-info btn-sm">Payslip</a><a href="{{ route('hr.payroll.edit', $value->id) }}" class="btn btn-primary btn-sm">Edit</a><form method="post" action="{{ route('hr.payroll.destroy') }}">@csrf<input type="hidden" name="hidden_id" value="{{ $value->id }}"><button type="submit" class="btn btn-danger btn-sm">Delete</button></form></td></tr>@endforeach</tbody></table></div>
        {{ $data->links('pagination::bootstrap-4') }}
    </div></div>
</div>
@endsection
